COOP detecta una posible mejora cuando hay una cadena muy larga de colaboraciones
MartinEGonzalez95/COOP pull request #19
Opened 2019-10-12 02:29 UTC by GTestay

##Propósito

Se agregó _RuleChainedColaborations_ que se encarga de validar si en un mensaje hay muchas colaboraciones encadenadas, esto permite al estudiante poder ver si no está rompiendo el encapsulamiento o estar haciendo mucha lógica en un solo lado.

##Cambios
Se agregó la clase abstracta _Rule_ que por ahora **sólo** define protocolo escencial a las reglas.

2019-10-12 17:07 UTC, MartinEGonzalez95 requested changes
Creo que quedo mal en el rebase y se borro la linea que hace que se limpien las reglas cuando estan arregladas. Creo que volviendo a poner la linea deberia todo andar igual, despues de eso y ver el tema de los comentarios estaria para mergear

Un plus que podemos hacer en este PR, es agregar mas casos a la clase DemoTest, para asi poder mostrar mejor que casos pensamos. Habria que cambiar los nombres de los existentes y ademas que la categoria sea un apply y un no-apply por cada regla. Si queres esto lo charlamos mejor en una call! :smile:

2019-10-12 17:07 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> +testTheAmountOfChainedColaborationsIsZeroWhenIsNotAMessageNode
Yo le pondria de nombre algo asi: testAmountOfChainedColaborationsIsZeroForNoMessageNodes

2019-10-12 17:07 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> +message: selectorName to: receiver
Esto es lo que usamos de Nahue? Sabes que significa el codigo 34? O la precendencia en el MessageNode?

2019-10-12 17:07 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> +searchMethodNode: selectorName
Este lo usamos tambien en la otra clase de test de reglas, no? Podriamos ver de extraerlo a un objetito mas interensate! :smile:

2019-10-12 17:07 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> -	performer cleanBeforeRunning: aMethodNode .
:warning: Aca estamos borrando lo que agregamos en el PR para que la regla se borre. En donde esta ahora?

2019-10-12 17:07 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> +	^ self withRules: {RuleCollectionSize new. RuleColaborationChain new} andPerformer: COOPPerformer new.! !
Creo que ya podemos pensar de extraerlo a una mensaje y a una coleccion no literal, no?

2019-10-12 17:07 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> +	^ 'Cuando ocurren muchas colaboraciones encadenadas se recomienda:
Antes de mergear hay que actualizar el documento con las descripciones! Y pedir review de Nahue

2019-10-12 17:07 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> +	^ 'Hay colaboraciones encadenadas'.! !
Lo pondria mas parecido al otro, algo tipo: 'Uso de colaboraciones encadenadas'

2019-10-13 18:53 UTC, GTestay commented on Cuis-University-COOP.pck.st
> +message: selectorName to: receiver
La verdad no me quedó claro para qué se usa la precedencia, si se lo _copié_ de cómo se crean, la verdad esto va a estar bueno porque podemos a futuro meter un builder de "métodos" ponele, le veo mucho futuro! :D

2019-10-13 18:56 UTC, GTestay commented on Cuis-University-COOP.pck.st
> +	^ self withRules: {RuleCollectionSize new. RuleColaborationChain new} andPerformer: COOPPerformer new.! !
si, me olvíde de comentarte que esto está la clase Rule>>#allRules y que devuelve este bichin.

2019-10-13 23:18 UTC, MartinEGonzalez95 requested changes
Deje unos comentarios menores!

Sigue borrada la linea que hace que se borre la regla cuando se soluciona en el metodo.
Creo que podes agarrar y volverla a poner a mano, porque lo demas sigue ahi

2019-10-13 23:18 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> +	"Construct the pane that shows the code.
Estos comentarios los podemos borrar :stuck_out_tongue:

2019-10-13 23:18 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> -	performer cleanBeforeRunning: aMethodNode .
:warning: Bump

2019-10-13 23:18 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> +	^ self withRules: Rule allRules andPerformer: COOPPerformer new.! !
Ahora que lo pienso, ponele que en el futuro alguien tiene un dominio de reglas de otra cosa. Creo que deberiamos hacer mas reducido el nombre de la clase para evitar futuras colisiones. Por ahora lo podemos dejar asi, pero creo que en un proximo PR deberiamos cambiar el nombre a COOPRules

2019-10-13 23:18 UTC, MartinEGonzalez95 commented on Cuis-University-COOP.pck.st
> +	COOPBrowser allInstancesDo: [:coopBrowser | coopBrowser addRule: aRule for:aMethodNode]! !
:cry: Me borraste la semantica aca jajaja

2019-10-14 15:45 UTC, MartinEGonzalez95 approved these changes
Excelente! Salimos con :fries:

2019-10-14 15:45 UTC, merged